# Generated by Django 5.2.5 on 2025-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms_users', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('engineer', 'Engineer'), ('admin', 'Admin')], default='engineer', max_length=20),
        ),
    ]
